import { z } from 'zod';

const trimmedOptionalStringSchema = z.preprocess((value) => {
  if (typeof value !== 'string') {
    return value;
  }

  const trimmed = value.trim();
  return trimmed.length === 0 ? undefined : trimmed;
}, z.string().optional());

const isoDateSchema = z.string().datetime({ offset: true }).or(z.string().date());

const decimalHoursSchema = z.coerce.number().min(0).max(24);

export const scheduleRangeQuerySchema = z.object({
  dateFrom: isoDateSchema.optional(),
  dateTo: isoDateSchema.optional(),
});

export const myTimeCardQuerySchema = z.object({
  periodStart: isoDateSchema.optional(),
});

export const listManagementSchedulesQuerySchema = z.object({
  orgUnitId: trimmedOptionalStringSchema,
  status: z.enum(['Draft', 'Published', 'Archived']).optional(),
  dateFrom: isoDateSchema.optional(),
  dateTo: isoDateSchema.optional(),
});

export const listManagementTimeCardsQuerySchema = z.object({
  status: z.enum(['Draft', 'Submitted', 'Approved', 'Rejected', 'Recalled']).optional(),
  orgUnitId: trimmedOptionalStringSchema,
  search: trimmedOptionalStringSchema,
  periodStart: isoDateSchema.optional(),
});

export const listManagementExceptionsQuerySchema = z.object({
  orgUnitId: trimmedOptionalStringSchema,
  periodStart: isoDateSchema.optional(),
});

export const timeEntryInputSchema = z.object({
  scheduledShiftId: trimmedOptionalStringSchema.nullable().optional(),
  workDate: isoDateSchema,
  earningType: z.enum(['Worked', 'Vacation', 'Sick', 'Personal', 'Unpaid', 'Leave', 'Holiday']),
  workedHours: decimalHoursSchema,
  startDateTime: isoDateSchema.nullable().optional(),
  endDateTime: isoDateSchema.nullable().optional(),
  breakMinutes: z.coerce.number().int().min(0).max(720).optional(),
  notes: trimmedOptionalStringSchema.nullable().optional(),
  exceptionFlags: z.array(z.string()).optional(),
  isAutoGenerated: z.boolean().optional(),
});

export const updateTimeCardEntriesSchema = z.object({
  entries: z.array(timeEntryInputSchema).min(1).max(100),
});

export const timeCardDecisionSchema = z.object({
  comments: trimmedOptionalStringSchema.nullable().optional(),
});

export const scheduledShiftInputSchema = z.object({
  employeeId: trimmedOptionalStringSchema.nullable().optional(),
  shiftTemplateId: trimmedOptionalStringSchema.nullable().optional(),
  shiftDate: isoDateSchema,
  startDateTime: isoDateSchema,
  endDateTime: isoDateSchema,
  breakMinutes: z.coerce.number().int().min(0).max(720).optional(),
  status: z.enum(['Scheduled', 'Published', 'Cancelled']).optional(),
  notes: trimmedOptionalStringSchema.nullable().optional(),
});

export const createScheduleSchema = z.object({
  orgUnitId: z.string().uuid(),
  periodStart: isoDateSchema,
  periodEnd: isoDateSchema,
  notes: trimmedOptionalStringSchema.nullable().optional(),
  shifts: z.array(scheduledShiftInputSchema).max(250).default([]),
});

export const updateScheduleSchema = z.object({
  notes: trimmedOptionalStringSchema.nullable().optional(),
  shifts: z.array(scheduledShiftInputSchema).max(250).optional(),
});

export const createLaborGroupSchema = z.object({
  code: z.string().trim().min(2).max(50),
  name: z.string().trim().min(2).max(150),
  status: z.enum(['Active', 'Inactive']).default('Active'),
  agreementReference: trimmedOptionalStringSchema.nullable().optional(),
  description: trimmedOptionalStringSchema.nullable().optional(),
});

export const updateLaborGroupSchema = createLaborGroupSchema.partial().refine((value) => Object.keys(value).length > 0, {
  message: 'At least one labor group field must be provided.',
});

export const createRuleProfileSchema = z.object({
  code: z.string().trim().min(2).max(50),
  name: z.string().trim().min(2).max(150),
  status: z.enum(['Active', 'Inactive']).default('Active'),
  laborGroupId: z.string().uuid().nullable().optional(),
  orgUnitId: z.string().uuid().nullable().optional(),
  positionId: z.string().uuid().nullable().optional(),
  classificationId: z.string().uuid().nullable().optional(),
  dailyOvertimeThreshold: z.coerce.number().min(0).max(24).default(8),
  weeklyOvertimeThreshold: z.coerce.number().min(0).max(168).default(40),
  doubleTimeThreshold: z.coerce.number().min(0).max(24).nullable().optional(),
  minimumRestHours: z.coerce.number().min(0).max(24).default(8),
  scheduledDailyHoursTarget: z.coerce.number().min(0).max(24).default(8),
  shiftPremiumRules: trimmedOptionalStringSchema.nullable().optional(),
  holidayTreatment: trimmedOptionalStringSchema.nullable().optional(),
  leaveTreatment: trimmedOptionalStringSchema.nullable().optional(),
});

export const updateRuleProfileSchema = createRuleProfileSchema.partial().refine((value) => Object.keys(value).length > 0, {
  message: 'At least one rule profile field must be provided.',
});

export const createShiftTemplateSchema = z.object({
  orgUnitId: z.string().uuid(),
  workRuleProfileId: z.string().uuid().nullable().optional(),
  code: z.string().trim().min(2).max(50),
  name: z.string().trim().min(2).max(150),
  startTime: z.string().trim().regex(/^\d{2}:\d{2}$/),
  endTime: z.string().trim().regex(/^\d{2}:\d{2}$/),
  unpaidBreakMinutes: z.coerce.number().int().min(0).max(720).default(0),
  paidBreakMinutes: z.coerce.number().int().min(0).max(720).default(0),
  status: z.enum(['Active', 'Inactive']).default('Active'),
});

export const updateShiftTemplateSchema = createShiftTemplateSchema.partial().refine((value) => Object.keys(value).length > 0, {
  message: 'At least one shift template field must be provided.',
});

export type ScheduleRangeQuery = z.infer<typeof scheduleRangeQuerySchema>;
export type MyTimeCardQuery = z.infer<typeof myTimeCardQuerySchema>;
export type ListManagementSchedulesQuery = z.infer<typeof listManagementSchedulesQuerySchema>;
export type ListManagementTimeCardsQuery = z.infer<typeof listManagementTimeCardsQuerySchema>;
export type ListManagementExceptionsQuery = z.infer<typeof listManagementExceptionsQuerySchema>;
export type UpdateTimeCardEntriesInput = z.infer<typeof updateTimeCardEntriesSchema>;
export type TimeCardDecisionInput = z.infer<typeof timeCardDecisionSchema>;
export type CreateScheduleInput = z.infer<typeof createScheduleSchema>;
export type UpdateScheduleInput = z.infer<typeof updateScheduleSchema>;
export type CreateLaborGroupInput = z.infer<typeof createLaborGroupSchema>;
export type UpdateLaborGroupInput = z.infer<typeof updateLaborGroupSchema>;
export type CreateRuleProfileInput = z.infer<typeof createRuleProfileSchema>;
export type UpdateRuleProfileInput = z.infer<typeof updateRuleProfileSchema>;
export type CreateShiftTemplateInput = z.infer<typeof createShiftTemplateSchema>;
export type UpdateShiftTemplateInput = z.infer<typeof updateShiftTemplateSchema>;
