import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import {
  AlertTriangle,
  CalendarDays,
  Clock3,
  FileClock,
  History,
  LoaderCircle,
  Plus,
  RefreshCcw,
  Send,
  TimerReset,
} from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAppSession } from '@/shared/auth/AppSessionProvider';
import { isFeatureEnabled } from '@/shared/features/feature-registry';
import {
  createMyTimeCard,
  getMySchedule,
  getMyTimeCard,
  getTimeAttendanceHistory,
  getTimeAttendanceSummary,
  recallMyTimeCard,
  submitMyTimeCard,
  updateMyTimeCardEntries,
  type MyScheduleWorkspace,
  type TimeAttendanceHistory,
  type TimeAttendanceSummary,
  type TimeCardRecord,
  type TimeEntryPayload,
  type TimeEntryRecord,
} from './time-attendance.api';
import { listLeaveRequests, type LeaveRequestRecord } from '@/pages/time-off/time-off.api';
import './TimeAttendancePage.css';

type TimeAttendanceTab = 'schedule' | 'time-card' | 'leave' | 'history';

function isTimeAttendanceTab(value: string | null): value is TimeAttendanceTab {
  return value === 'schedule' || value === 'time-card' || value === 'leave' || value === 'history';
}

interface EditableEntry {
  id: string;
  scheduledShiftId: string | null;
  workDate: string;
  earningType: TimeEntryRecord['earningType'];
  workedHours: string;
  startDateTime: string;
  endDateTime: string;
  breakMinutes: string;
  notes: string;
  exceptionFlags: string[];
  isAutoGenerated: boolean;
}

const entryTypeOptions: Array<TimeEntryRecord['earningType']> = [
  'Worked',
  'Vacation',
  'Sick',
  'Personal',
  'Unpaid',
  'Leave',
  'Holiday',
];

function formatShortDate(value: string | null) {
  if (!value) {
    return 'TBD';
  }

  return new Intl.DateTimeFormat('en-CA', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
  }).format(new Date(value));
}

function formatShortTime(value: string | null) {
  if (!value) {
    return 'TBD';
  }

  return new Intl.DateTimeFormat('en-CA', {
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(value));
}

function formatHours(value: number) {
  return new Intl.NumberFormat(undefined, {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value);
}

function toDateInput(value: string | null) {
  return value ? value.slice(0, 10) : '';
}

function toDateTimeInput(value: string | null) {
  if (!value) {
    return '';
  }

  const date = new Date(value);
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  const hours = `${date.getHours()}`.padStart(2, '0');
  const minutes = `${date.getMinutes()}`.padStart(2, '0');
  return `${year}-${month}-${day}T${hours}:${minutes}`;
}

function fromTimeEntry(entry: TimeEntryRecord): EditableEntry {
  return {
    id: entry.id,
    scheduledShiftId: entry.scheduledShiftId,
    workDate: toDateInput(entry.workDate),
    earningType: entry.earningType,
    workedHours: String(entry.workedHours),
    startDateTime: toDateTimeInput(entry.startDateTime),
    endDateTime: toDateTimeInput(entry.endDateTime),
    breakMinutes: String(entry.breakMinutes),
    notes: entry.notes ?? '',
    exceptionFlags: entry.exceptionFlags,
    isAutoGenerated: entry.isAutoGenerated,
  };
}

function createBlankEntry(): EditableEntry {
  return {
    id: `new-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    scheduledShiftId: null,
    workDate: toDateInput(new Date().toISOString()),
    earningType: 'Worked',
    workedHours: '8',
    startDateTime: '',
    endDateTime: '',
    breakMinutes: '0',
    notes: '',
    exceptionFlags: [],
    isAutoGenerated: false,
  };
}

function getCurrentWeekRange() {
  const now = new Date();
  const day = now.getDay();
  const offsetToMonday = day === 0 ? -6 : 1 - day;
  const start = new Date(now);
  start.setDate(now.getDate() + offsetToMonday);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(start.getDate() + 13);
  end.setHours(23, 59, 59, 999);
  return {
    dateFrom: toDateInput(start.toISOString()),
    dateTo: toDateInput(end.toISOString()),
  };
}

export function TimeAttendancePage() {
  const { session } = useAppSession();
  const [searchParams, setSearchParams] = useSearchParams();
  const [tab, setTab] = useState<TimeAttendanceTab>(() => {
    const requestedTab = searchParams.get('tab');
    return isTimeAttendanceTab(requestedTab) ? requestedTab : 'schedule';
  });
  const [summary, setSummary] = useState<TimeAttendanceSummary | null>(null);
  const [schedule, setSchedule] = useState<MyScheduleWorkspace | null>(null);
  const [timeCard, setTimeCard] = useState<TimeCardRecord | null>(null);
  const [history, setHistory] = useState<TimeAttendanceHistory | null>(null);
  const [leaveRequests, setLeaveRequests] = useState<LeaveRequestRecord[]>([]);
  const [editableEntries, setEditableEntries] = useState<EditableEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const timeOffRequestsEnabled = isFeatureEnabled(session?.features, 'time_off_requests');
  const weekRange = useMemo(() => getCurrentWeekRange(), []);

  const loadWorkspace = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const [nextSummary, nextSchedule, nextTimeCard, nextHistory, nextLeaveRequests] = await Promise.all([
        getTimeAttendanceSummary(),
        getMySchedule(weekRange),
        getMyTimeCard(),
        getTimeAttendanceHistory(),
        listLeaveRequests({ page: 1, limit: 25 }),
      ]);

      setSummary(nextSummary);
      setSchedule(nextSchedule);
      setTimeCard(nextTimeCard);
      setEditableEntries(nextTimeCard?.entries.map(fromTimeEntry) ?? []);
      setHistory(nextHistory);
      setLeaveRequests(nextLeaveRequests.data);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : 'Unable to load time and attendance.');
    } finally {
      setLoading(false);
    }
  }, [weekRange]);

  useEffect(() => {
    void loadWorkspace();
  }, [loadWorkspace]);

  useEffect(() => {
    const requestedTab = searchParams.get('tab');
    if (isTimeAttendanceTab(requestedTab) && requestedTab !== tab) {
      setTab(requestedTab);
    }
  }, [searchParams, tab]);

  const setActiveTab = (nextTab: TimeAttendanceTab) => {
    setTab(nextTab);
    const nextParams = new URLSearchParams(searchParams);

    if (nextTab === 'schedule') {
      nextParams.delete('tab');
    } else {
      nextParams.set('tab', nextTab);
    }

    setSearchParams(nextParams, { replace: true });
  };

  const scheduleDays = useMemo(() => {
    if (!schedule) {
      return [];
    }

    const grouped = new Map<string, {
      date: string;
      shifts: MyScheduleWorkspace['shifts'];
      leave: MyScheduleWorkspace['approvedLeave'];
      holidays: MyScheduleWorkspace['holidays'];
    }>();

    for (const shift of schedule.shifts) {
      const dateKey = toDateInput(shift.shiftDate);
      const current = grouped.get(dateKey) ?? { date: dateKey, shifts: [], leave: [], holidays: [] };
      current.shifts.push(shift);
      grouped.set(dateKey, current);
    }

    for (const leave of schedule.approvedLeave) {
      const startDate = leave.startDate ? new Date(leave.startDate) : null;
      const endDate = leave.endDate ? new Date(leave.endDate) : null;
      if (!startDate || !endDate) {
        continue;
      }

      const pointer = new Date(startDate);
      while (pointer <= endDate) {
        const dateKey = toDateInput(pointer.toISOString());
        const current = grouped.get(dateKey) ?? { date: dateKey, shifts: [], leave: [], holidays: [] };
        current.leave.push(leave);
        grouped.set(dateKey, current);
        pointer.setDate(pointer.getDate() + 1);
      }
    }

    for (const holiday of schedule.holidays) {
      const dateKey = toDateInput(holiday.holidayDate);
      const current = grouped.get(dateKey) ?? { date: dateKey, shifts: [], leave: [], holidays: [] };
      current.holidays.push(holiday);
      grouped.set(dateKey, current);
    }

    return Array.from(grouped.values()).sort((left, right) => left.date.localeCompare(right.date));
  }, [schedule]);

  const currentPeriodLabel = useMemo(() => {
    if (!timeCard?.periodStart || !timeCard.periodEnd) {
      return 'Current pay period';
    }

    return `${formatShortDate(timeCard.periodStart)} to ${formatShortDate(timeCard.periodEnd)}`;
  }, [timeCard?.periodEnd, timeCard?.periodStart]);

  const editableTimeCard = Boolean(timeCard && ['Draft', 'Rejected', 'Recalled'].includes(timeCard.status));
  const historyCards = useMemo(
    () => (history?.timeCards ?? []).filter((card) => card.id !== timeCard?.id),
    [history?.timeCards, timeCard?.id],
  );

  const createCard = async () => {
    setSaving(true);
    setError(null);

    try {
      const created = await createMyTimeCard();
      setTimeCard(created);
      setEditableEntries(created.entries.map(fromTimeEntry));
      await loadWorkspace();
      setTab('time-card');
    } catch (createError) {
      setError(createError instanceof Error ? createError.message : 'Unable to create the time card.');
    } finally {
      setSaving(false);
    }
  };

  const saveEntries = async () => {
    if (!timeCard) {
      return;
    }

    setSaving(true);
    setError(null);

    try {
      const payload: TimeEntryPayload[] = editableEntries
        .filter((entry) => entry.workDate && Number(entry.workedHours) > 0)
        .map((entry) => ({
          scheduledShiftId: entry.scheduledShiftId,
          workDate: entry.workDate,
          earningType: entry.earningType,
          workedHours: Number(entry.workedHours),
          startDateTime: entry.startDateTime || null,
          endDateTime: entry.endDateTime || null,
          breakMinutes: Number(entry.breakMinutes || 0),
          notes: entry.notes.trim() || null,
          exceptionFlags: entry.exceptionFlags,
          isAutoGenerated: entry.isAutoGenerated,
        }));

      const saved = await updateMyTimeCardEntries(timeCard.id, payload);
      setTimeCard(saved);
      setEditableEntries(saved.entries.map(fromTimeEntry));
      await loadWorkspace();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : 'Unable to save the time card.');
    } finally {
      setSaving(false);
    }
  };

  const submitCard = async () => {
    if (!timeCard) {
      return;
    }

    setSaving(true);
    setError(null);

    try {
      const submitted = await submitMyTimeCard(timeCard.id);
      setTimeCard(submitted);
      setEditableEntries(submitted.entries.map(fromTimeEntry));
      await loadWorkspace();
    } catch (submitError) {
      setError(submitError instanceof Error ? submitError.message : 'Unable to submit the time card.');
    } finally {
      setSaving(false);
    }
  };

  const recallCard = async () => {
    if (!timeCard) {
      return;
    }

    setSaving(true);
    setError(null);

    try {
      const recalled = await recallMyTimeCard(timeCard.id);
      setTimeCard(recalled);
      setEditableEntries(recalled.entries.map(fromTimeEntry));
      await loadWorkspace();
    } catch (recallError) {
      setError(recallError instanceof Error ? recallError.message : 'Unable to recall the time card.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <section className="time-attendance-page">
      <div className="card time-attendance-hero">
        <div className="page-header time-attendance-header">
          <div>
            <span className="time-attendance-eyebrow">My Work</span>
            <h1 className="page-title">Time &amp; Attendance</h1>
            <p className="page-subtitle">Stay on top of your weekly schedule, current pay-period time card, leave, and prior approvals without switching between disconnected tools.</p>
          </div>
          <div className="time-attendance-header-actions">
            <button type="button" className="button button-outline" onClick={() => { void loadWorkspace(); }}>
              <RefreshCcw size={16} />
              Refresh
            </button>
            {!timeCard ? (
              <button type="button" className="button" onClick={() => { void createCard(); }} disabled={saving || !summary?.access.accountLinked}>
                <Plus size={16} />
                Create time card
              </button>
            ) : null}
          </div>
        </div>

        {!summary?.access.accountLinked ? (
          <div className="time-attendance-banner">
            <AlertTriangle size={16} />
            <span>Your account is not linked to an employee profile yet. Schedule, time-card, and leave activity will remain unavailable until HR completes the link.</span>
          </div>
        ) : null}

        {error ? (
          <div className="time-attendance-banner time-attendance-banner-error">
            <AlertTriangle size={16} />
            <span>{error}</span>
          </div>
        ) : null}

        <div className="time-attendance-metrics">
          <MetricCard label="Current pay period" value={timeCard?.status ?? 'Not started'} detail={currentPeriodLabel} icon={<FileClock size={18} />} />
          <MetricCard label="Scheduled this week" value={`${formatHours(summary?.scheduledHoursThisWeek ?? 0)} hrs`} detail="Published shifts in the current two-week view" icon={<CalendarDays size={18} />} />
          <MetricCard label="Approved leave upcoming" value={String(summary?.approvedLeaveUpcoming ?? 0)} detail="Approved requests still ahead" icon={<Clock3 size={18} />} />
          <MetricCard label="Exception flags" value={String(summary?.exceptionCount ?? 0)} detail="Time-card or scheduling follow-up" icon={<AlertTriangle size={18} />} />
        </div>
      </div>

      <div className="card">
        <div className="time-attendance-tabs" role="tablist" aria-label="Time and attendance tabs">
          {([
            ['schedule', 'My Schedule'],
            ['time-card', 'My Time Card'],
            ['leave', 'Leave'],
            ['history', 'History'],
          ] as const).map(([value, label]) => (
            <button
              key={value}
              type="button"
              className={`time-attendance-tab ${tab === value ? 'time-attendance-tab-active' : ''}`}
              onClick={() => setActiveTab(value)}
            >
              {label}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="time-attendance-state">
            <LoaderCircle className="time-attendance-spin" size={18} />
            <span>Loading time and attendance...</span>
          </div>
        ) : null}

        {!loading && tab === 'schedule' ? (
          <div className="time-attendance-section">
            <div className="card-header">
              <div>
                <h3 className="card-title">My Schedule</h3>
                <p className="card-subtitle">Published shifts, approved leave, and holidays for the current planning window.</p>
              </div>
            </div>

            <div className="time-attendance-schedule-grid">
              {scheduleDays.length === 0 ? (
                <div className="time-attendance-empty">
                  <CalendarDays size={18} />
                  <span>No published shifts, leave, or holidays are in this window yet.</span>
                </div>
              ) : scheduleDays.map((day) => (
                <article key={day.date} className="time-attendance-day-card">
                  <div className="time-attendance-day-header">
                    <strong>{formatShortDate(day.date)}</strong>
                    <span>{day.shifts.length} shift{day.shifts.length === 1 ? '' : 's'}</span>
                  </div>

                  <div className="time-attendance-day-list">
                    {day.shifts.map((shift) => (
                      <div key={shift.id} className="time-attendance-inline-row">
                        <div>
                          <div className="time-attendance-inline-title">{shift.shiftTemplate?.name ?? 'Scheduled shift'}</div>
                          <div className="time-attendance-inline-meta">{formatShortTime(shift.startDateTime)} to {formatShortTime(shift.endDateTime)} | {formatHours(shift.scheduledHours)} hrs</div>
                        </div>
                        <span className="badge badge-primary">{shift.orgUnit?.code ?? 'ORG'}</span>
                      </div>
                    ))}

                    {day.leave.map((leave) => (
                      <div key={leave.id} className="time-attendance-inline-row time-attendance-inline-row-leave">
                        <div>
                          <div className="time-attendance-inline-title">{leave.leaveType.name}</div>
                          <div className="time-attendance-inline-meta">{formatHours(leave.requestedHours)} hrs approved</div>
                        </div>
                        <span className="badge badge-success">{leave.status}</span>
                      </div>
                    ))}

                    {day.holidays.map((holiday) => (
                      <div key={holiday.id} className="time-attendance-inline-row time-attendance-inline-row-holiday">
                        <div>
                          <div className="time-attendance-inline-title">{holiday.name}</div>
                          <div className="time-attendance-inline-meta">{holiday.note ?? 'Holiday'}</div>
                        </div>
                        <span className="badge badge-warning">Holiday</span>
                      </div>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </div>
        ) : null}

        {!loading && tab === 'time-card' ? (
          <div className="time-attendance-section">
            <div className="card-header">
              <div>
                <h3 className="card-title">My Time Card</h3>
                <p className="card-subtitle">Keep the current pay period accurate, then submit it for manager review.</p>
              </div>
            </div>

            {!timeCard ? (
              <div className="time-attendance-empty">
                <FileClock size={18} />
                <div className="time-attendance-empty-copy">
                  <strong>No current time card exists yet.</strong>
                  <span>Create the current pay-period card to start entering hours.</span>
                </div>
                <button type="button" className="button" onClick={() => { void createCard(); }} disabled={saving || !summary?.access.accountLinked}>
                  <Plus size={16} />
                  Create time card
                </button>
              </div>
            ) : (
              <>
                <div className="time-attendance-card-meta">
                  <MetricCard label="Status" value={timeCard.status} detail={currentPeriodLabel} icon={<Clock3 size={18} />} />
                  <MetricCard label="Regular" value={`${formatHours(timeCard.regularHours)} hrs`} detail="Worked hours within threshold" icon={<FileClock size={18} />} />
                  <MetricCard label="Overtime" value={`${formatHours(timeCard.overtimeHours)} hrs`} detail="Calculated overtime this period" icon={<AlertTriangle size={18} />} />
                  <MetricCard label="Leave / Holiday" value={`${formatHours(timeCard.leaveHours + timeCard.holidayHours)} hrs`} detail="Auto-filled non-worked hours" icon={<CalendarDays size={18} />} />
                </div>

                {timeCard.approvalComment ? (
                  <div className="time-attendance-banner time-attendance-banner-info">
                    <AlertTriangle size={16} />
                    <span>{timeCard.approvalComment}</span>
                  </div>
                ) : null}

                <div className="time-attendance-table-shell">
                  <table className="data-table">
                    <thead>
                      <tr>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Hours</th>
                        <th>Start</th>
                        <th>End</th>
                        <th>Break</th>
                        <th>Notes</th>
                      </tr>
                    </thead>
                    <tbody>
                      {editableEntries.length === 0 ? (
                        <tr>
                          <td colSpan={7} className="time-attendance-empty-cell">No entries are in the current time card yet.</td>
                        </tr>
                      ) : editableEntries.map((entry) => {
                        const rowLocked = !editableTimeCard || (entry.isAutoGenerated && entry.earningType !== 'Worked');
                        return (
                          <tr key={entry.id}>
                            <td><input className="time-attendance-table-input" type="date" value={entry.workDate} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, workDate: event.target.value } : candidate))} /></td>
                            <td>
                              <select className="time-attendance-table-input" value={entry.earningType} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, earningType: event.target.value as TimeEntryRecord['earningType'] } : candidate))}>
                                {entryTypeOptions.map((option) => <option key={option} value={option}>{option}</option>)}
                              </select>
                            </td>
                            <td><input className="time-attendance-table-input" type="number" min="0" max="24" step="0.25" value={entry.workedHours} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, workedHours: event.target.value } : candidate))} /></td>
                            <td><input className="time-attendance-table-input" type="datetime-local" value={entry.startDateTime} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, startDateTime: event.target.value } : candidate))} /></td>
                            <td><input className="time-attendance-table-input" type="datetime-local" value={entry.endDateTime} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, endDateTime: event.target.value } : candidate))} /></td>
                            <td><input className="time-attendance-table-input" type="number" min="0" max="720" step="15" value={entry.breakMinutes} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, breakMinutes: event.target.value } : candidate))} /></td>
                            <td><input className="time-attendance-table-input" type="text" value={entry.notes} disabled={rowLocked} onChange={(event) => setEditableEntries((current) => current.map((candidate) => candidate.id === entry.id ? { ...candidate, notes: event.target.value } : candidate))} /></td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>

                <div className="time-attendance-table-actions">
                  {editableTimeCard ? <button type="button" className="button button-outline" onClick={() => setEditableEntries((current) => [...current, createBlankEntry()])}><Plus size={16} />Add row</button> : null}
                  {editableTimeCard ? <button type="button" className="button button-outline" onClick={() => { void saveEntries(); }} disabled={saving}><FileClock size={16} />Save draft</button> : null}
                  {editableTimeCard ? <button type="button" className="button" onClick={() => { void submitCard(); }} disabled={saving}><Send size={16} />Submit</button> : null}
                  {timeCard.status === 'Submitted' ? <button type="button" className="button button-outline" onClick={() => { void recallCard(); }} disabled={saving}><TimerReset size={16} />Recall</button> : null}
                </div>
              </>
            )}
          </div>
        ) : null}

        {!loading && tab === 'leave' ? (
          <div className="time-attendance-section">
            <div className="card-header">
              <div>
                <h3 className="card-title">Leave</h3>
                <p className="card-subtitle">Keep leave context inside the same workforce-time workspace, then open the focused leave request flow only when you need to create, edit, or cancel a request.</p>
              </div>
              <Link to="/time-off" className="button">Manage leave requests</Link>
            </div>

            {!timeOffRequestsEnabled ? (
              <div className="time-attendance-banner">
                <AlertTriangle size={16} />
                <span>Time off requests are currently turned off by your administrator. Existing leave history still appears here.</span>
              </div>
            ) : null}

            <div className="time-attendance-leave-grid">
              {leaveRequests.length === 0 ? (
                <div className="time-attendance-empty">
                  <CalendarDays size={18} />
                  <span>No leave requests are currently in your history.</span>
                </div>
              ) : leaveRequests.slice(0, 8).map((request) => (
                <article key={request.id} className="time-attendance-leave-card">
                  <div className="time-attendance-leave-card-header">
                    <div>
                      <strong>{request.leaveType?.name ?? 'Leave request'}</strong>
                      <div className="time-attendance-inline-meta">{formatShortDate(request.startDate)} to {formatShortDate(request.endDate)}</div>
                    </div>
                    <span className={`badge ${request.status === 'Approved' ? 'badge-success' : request.status === 'Pending' ? 'badge-warning' : 'badge-primary'}`}>{request.status}</span>
                  </div>
                  <div className="time-attendance-inline-meta">{formatHours(request.requestedHours)} hrs | Routed to {request.approver?.fullName ?? 'HR Operations'}</div>
                  {request.notes ? <p className="time-attendance-leave-note">{request.notes}</p> : null}
                </article>
              ))}
            </div>
          </div>
        ) : null}

        {!loading && tab === 'history' ? (
          <div className="time-attendance-section">
            <div className="card-header">
              <div>
                <h3 className="card-title">History</h3>
                <p className="card-subtitle">Previous time cards, leave history, and approval outcomes across prior periods.</p>
              </div>
            </div>

            <div className="time-attendance-history-grid">
              <div className="time-attendance-history-panel">
                <h4>Previous time cards</h4>
                {historyCards.length === 0 ? (
                  <div className="time-attendance-empty">
                    <History size={18} />
                    <span>No previous time cards are available yet.</span>
                  </div>
                ) : historyCards.map((card) => (
                  <div key={card.id} className="time-attendance-history-row">
                    <div>
                      <strong>{formatShortDate(card.periodStart)} to {formatShortDate(card.periodEnd)}</strong>
                      <div className="time-attendance-inline-meta">{formatHours(card.totalWorkedHours)} worked | {formatHours(card.overtimeHours)} OT | {card.exceptionCount} exceptions</div>
                    </div>
                    <span className={`badge ${card.status === 'Approved' ? 'badge-success' : card.status === 'Rejected' ? 'badge-danger' : 'badge-warning'}`}>{card.status}</span>
                  </div>
                ))}
              </div>

              <div className="time-attendance-history-panel">
                <h4>Leave history</h4>
                {(history?.leaveRequests ?? []).length === 0 ? (
                  <div className="time-attendance-empty">
                    <CalendarDays size={18} />
                    <span>No leave history is available yet.</span>
                  </div>
                ) : history?.leaveRequests.map((request) => (
                  <div key={request.id} className="time-attendance-history-row">
                    <div>
                      <strong>{request.leaveType.name}</strong>
                      <div className="time-attendance-inline-meta">{formatShortDate(request.startDate)} to {formatShortDate(request.endDate)} | {formatHours(request.requestedHours)} hrs</div>
                    </div>
                    <span className={`badge ${request.status === 'Approved' ? 'badge-success' : request.status === 'Pending' ? 'badge-warning' : 'badge-primary'}`}>{request.status}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </section>
  );
}

function MetricCard({
  label,
  value,
  detail,
  icon,
}: {
  label: string;
  value: string;
  detail: string;
  icon: ReactNode;
}) {
  return (
    <div className="time-attendance-metric-card">
      <div className="time-attendance-metric-header">
        <span className="time-attendance-metric-label">{label}</span>
        <span className="time-attendance-metric-icon">{icon}</span>
      </div>
      <strong className="time-attendance-metric-value">{value}</strong>
      <span className="time-attendance-metric-detail">{detail}</span>
    </div>
  );
}
