import { apiRequest, buildQuery } from '@/shared/lib/api';

export interface TimeAttendanceSummary {
  access: {
    accountLinked: boolean;
  };
  currentTimeCard: {
    id: string;
    status: string;
    periodStart: string | null;
    periodEnd: string | null;
  } | null;
  scheduledHoursThisWeek: number;
  approvedLeaveUpcoming: number;
  exceptionCount: number;
}

export interface TimeAttendanceOrgUnit {
  id: string;
  code: string;
  name: string;
  type: string;
}

export interface TimeAttendanceEmployee {
  id: string;
  employeeNumber: string;
  fullName: string;
  department: string;
  jobTitle: string;
}

export interface ScheduledShiftRecord {
  id: string;
  shiftDate: string | null;
  startDateTime: string | null;
  endDateTime: string | null;
  breakMinutes: number;
  scheduledHours: number;
  status: string;
  notes: string | null;
  orgUnit: TimeAttendanceOrgUnit | null;
  employee: TimeAttendanceEmployee | null;
  shiftTemplate: {
    id: string;
    code: string;
    name: string;
  } | null;
}

export interface MyScheduleWorkspace {
  shifts: ScheduledShiftRecord[];
  approvedLeave: Array<{
    id: string;
    startDate: string | null;
    endDate: string | null;
    requestedHours: number;
    status: string;
    leaveType: {
      id: string;
      code: string;
      name: string;
    };
  }>;
  holidays: Array<{
    id: string;
    name: string;
    holidayDate: string | null;
    note: string | null;
    orgUnit: TimeAttendanceOrgUnit | null;
  }>;
}

export interface TimeEntryRecord {
  id: string;
  scheduledShiftId: string | null;
  workDate: string | null;
  earningType: 'Worked' | 'Vacation' | 'Sick' | 'Personal' | 'Unpaid' | 'Leave' | 'Holiday';
  workedHours: number;
  startDateTime: string | null;
  endDateTime: string | null;
  breakMinutes: number;
  notes: string | null;
  exceptionFlags: string[];
  isAutoGenerated: boolean;
}

export interface TimeCardRecord {
  id: string;
  status: 'Draft' | 'Submitted' | 'Approved' | 'Rejected' | 'Recalled';
  periodStart: string | null;
  periodEnd: string | null;
  submittedAt: string | null;
  approvedAt: string | null;
  rejectedAt: string | null;
  recalledAt: string | null;
  approvalComment: string | null;
  regularHours: number;
  overtimeHours: number;
  doubleTimeHours: number;
  leaveHours: number;
  holidayHours: number;
  totalWorkedHours: number;
  exceptionCount: number;
  employee: TimeAttendanceEmployee | null;
  approver: TimeAttendanceEmployee | null;
  orgUnit: TimeAttendanceOrgUnit | null;
  entries: TimeEntryRecord[];
}

export interface TimeAttendanceHistory {
  timeCards: TimeCardRecord[];
  leaveRequests: Array<{
    id: string;
    startDate: string | null;
    endDate: string | null;
    requestedHours: number;
    status: string;
    leaveType: {
      code: string;
      name: string;
    };
  }>;
}

export interface ManagementSummary {
  pendingApprovals: number;
  openExceptions: number;
  overtimeHoursCurrentPeriod: number;
  uncoveredShifts: number;
}

export interface WorkScheduleRecord {
  id: string;
  periodStart: string | null;
  periodEnd: string | null;
  status: string;
  notes: string | null;
  publishedAt: string | null;
  orgUnit: TimeAttendanceOrgUnit | null;
  shiftCount: number;
  uncoveredShiftCount: number;
  shifts: ScheduledShiftRecord[];
}

export interface LaborGroupRecord {
  id: string;
  code: string;
  name: string;
  status: string;
  agreementReference: string | null;
  description: string | null;
  employeeCount: number;
  ruleProfileCount: number;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface RuleProfileRecord {
  id: string;
  code: string;
  name: string;
  status: string;
  laborGroup: LaborGroupRecord | null;
  orgUnit: TimeAttendanceOrgUnit | null;
  position: {
    id: string;
    positionCode: string;
    title: string;
  } | null;
  classification: {
    id: string;
    code: string;
    title: string;
  } | null;
  dailyOvertimeThreshold: number;
  weeklyOvertimeThreshold: number;
  doubleTimeThreshold: number | null;
  minimumRestHours: number;
  scheduledDailyHoursTarget: number;
  shiftPremiumRules: string | null;
  holidayTreatment: string | null;
  leaveTreatment: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface ShiftTemplateRecord {
  id: string;
  code: string;
  name: string;
  startTime: string;
  endTime: string;
  unpaidBreakMinutes: number;
  paidBreakMinutes: number;
  status: string;
  orgUnit: TimeAttendanceOrgUnit | null;
  workRuleProfile: {
    id: string;
    code: string;
    name: string;
  } | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface TimeAttendanceException {
  id: string;
  category: string;
  severity: string;
  title: string;
  detail: string;
  date: string | null;
  employee: TimeAttendanceEmployee | null;
  orgUnit: TimeAttendanceOrgUnit | null;
  relatedEntityType: string;
  relatedEntityId: string;
}

export interface TimeAttendanceReport {
  overview: {
    pendingApprovals: number;
    openExceptions: number;
    uncoveredShifts: number;
    overtimeHours: number;
  };
  timeCards: Array<{
    id: string;
    employee: {
      id: string;
      employeeNumber: string;
      fullName: string;
      department: string;
    } | null;
    orgUnit: TimeAttendanceOrgUnit | null;
    status: string;
    periodStart: string | null;
    periodEnd: string | null;
    overtimeHours: number;
    exceptionCount: number;
    approvalComment: string | null;
  }>;
  coverage: Array<{
    id: string;
    orgUnit: TimeAttendanceOrgUnit | null;
    periodStart: string | null;
    periodEnd: string | null;
    status: string;
    shiftCount: number;
    uncoveredShiftCount: number;
  }>;
  exceptions: Array<{
    id: string;
    category: string;
    employee: string;
    orgUnit: string;
    date: string | null;
    detail: string;
  }>;
}

export interface TimeEntryPayload {
  scheduledShiftId?: string | null;
  workDate: string;
  earningType: TimeEntryRecord['earningType'];
  workedHours: number;
  startDateTime?: string | null;
  endDateTime?: string | null;
  breakMinutes?: number;
  notes?: string | null;
  exceptionFlags?: string[];
  isAutoGenerated?: boolean;
}

export interface ScheduleShiftPayload {
  employeeId?: string | null;
  shiftTemplateId?: string | null;
  shiftDate: string;
  startDateTime: string;
  endDateTime: string;
  breakMinutes?: number;
  status?: 'Scheduled' | 'Published' | 'Cancelled';
  notes?: string | null;
}

export interface SchedulePayload {
  orgUnitId: string;
  periodStart: string;
  periodEnd: string;
  notes?: string | null;
  shifts: ScheduleShiftPayload[];
}

export interface RuleProfilePayload {
  code: string;
  name: string;
  status?: 'Active' | 'Inactive';
  laborGroupId?: string | null;
  orgUnitId?: string | null;
  positionId?: string | null;
  classificationId?: string | null;
  dailyOvertimeThreshold?: number;
  weeklyOvertimeThreshold?: number;
  doubleTimeThreshold?: number | null;
  minimumRestHours?: number;
  scheduledDailyHoursTarget?: number;
  shiftPremiumRules?: string | null;
  holidayTreatment?: string | null;
  leaveTreatment?: string | null;
}

export interface LaborGroupPayload {
  code: string;
  name: string;
  status?: 'Active' | 'Inactive';
  agreementReference?: string | null;
  description?: string | null;
}

export interface ShiftTemplatePayload {
  orgUnitId: string;
  workRuleProfileId?: string | null;
  code: string;
  name: string;
  startTime: string;
  endTime: string;
  unpaidBreakMinutes?: number;
  paidBreakMinutes?: number;
  status?: 'Active' | 'Inactive';
}

export async function getTimeAttendanceSummary() {
  const response = await apiRequest<{ success: true; data: TimeAttendanceSummary }>('/api/time-attendance/summary', {}, 'Unable to load time and attendance summary.');
  return response.data;
}

export async function getMySchedule(query: { dateFrom?: string; dateTo?: string } = {}) {
  const response = await apiRequest<{ success: true; data: MyScheduleWorkspace }>(`/api/time-attendance/my-schedule${buildQuery(query)}`, {}, 'Unable to load your schedule.');
  return response.data;
}

export async function getMyTimeCard(periodStart?: string) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord | null }>(`/api/time-attendance/my-time-card${buildQuery({ periodStart })}`, {}, 'Unable to load your time card.');
  return response.data;
}

export async function createMyTimeCard() {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>('/api/time-attendance/my-time-card', {
    method: 'POST',
  }, 'Unable to create your time card.');
  return response.data;
}

export async function updateMyTimeCardEntries(id: string, entries: TimeEntryPayload[]) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>(`/api/time-attendance/my-time-card/${id}/entries`, {
    method: 'PUT',
    body: JSON.stringify({ entries }),
  }, 'Unable to update the time card.');
  return response.data;
}

export async function submitMyTimeCard(id: string) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>(`/api/time-attendance/my-time-card/${id}/submit`, {
    method: 'POST',
  }, 'Unable to submit the time card.');
  return response.data;
}

export async function recallMyTimeCard(id: string) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>(`/api/time-attendance/my-time-card/${id}/recall`, {
    method: 'POST',
  }, 'Unable to recall the time card.');
  return response.data;
}

export async function getTimeAttendanceHistory() {
  const response = await apiRequest<{ success: true; data: TimeAttendanceHistory }>('/api/time-attendance/history', {}, 'Unable to load time and attendance history.');
  return response.data;
}

export async function getManagementSummary() {
  const response = await apiRequest<{ success: true; data: ManagementSummary }>('/api/time-attendance/management/summary', {}, 'Unable to load workforce time summary.');
  return response.data;
}

export async function listManagementSchedules(query: { orgUnitId?: string; status?: string; dateFrom?: string; dateTo?: string } = {}) {
  const response = await apiRequest<{ success: true; data: WorkScheduleRecord[] }>(`/api/time-attendance/management/schedules${buildQuery(query)}`, {}, 'Unable to load schedules.');
  return response.data;
}

export async function createManagementSchedule(payload: SchedulePayload) {
  const response = await apiRequest<{ success: true; data: WorkScheduleRecord | null }>('/api/time-attendance/management/schedules', {
    method: 'POST',
    body: JSON.stringify(payload),
  }, 'Unable to create the schedule.');
  return response.data;
}

export async function updateManagementSchedule(id: string, payload: Partial<Omit<SchedulePayload, 'orgUnitId' | 'periodStart' | 'periodEnd'>>) {
  const response = await apiRequest<{ success: true; data: WorkScheduleRecord | null }>(`/api/time-attendance/management/schedules/${id}`, {
    method: 'PUT',
    body: JSON.stringify(payload),
  }, 'Unable to update the schedule.');
  return response.data;
}

export async function publishManagementSchedule(id: string) {
  const response = await apiRequest<{ success: true; data: { id: string } }>(`/api/time-attendance/management/schedules/${id}/publish`, {
    method: 'POST',
  }, 'Unable to publish the schedule.');
  return response.data;
}

export async function listManagementTimeCards(query: { status?: string; orgUnitId?: string; search?: string; periodStart?: string } = {}) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord[] }>(`/api/time-attendance/management/time-cards${buildQuery(query)}`, {}, 'Unable to load management time cards.');
  return response.data;
}

export async function getManagementTimeCardDetail(id: string) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord | null }>(`/api/time-attendance/management/time-cards/${id}`, {}, 'Unable to load the time card.');
  return response.data;
}

export async function approveManagementTimeCard(id: string, comments?: string | null) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>(`/api/time-attendance/management/time-cards/${id}/approve`, {
    method: 'POST',
    body: JSON.stringify({ comments: comments ?? null }),
  }, 'Unable to approve the time card.');
  return response.data;
}

export async function rejectManagementTimeCard(id: string, comments?: string | null) {
  const response = await apiRequest<{ success: true; data: TimeCardRecord }>(`/api/time-attendance/management/time-cards/${id}/reject`, {
    method: 'POST',
    body: JSON.stringify({ comments: comments ?? null }),
  }, 'Unable to reject the time card.');
  return response.data;
}

export async function listManagementExceptions(query: { orgUnitId?: string; periodStart?: string } = {}) {
  const response = await apiRequest<{ success: true; data: TimeAttendanceException[] }>(`/api/time-attendance/management/exceptions${buildQuery(query)}`, {}, 'Unable to load workforce time exceptions.');
  return response.data;
}

export async function listLaborGroups() {
  const response = await apiRequest<{ success: true; data: LaborGroupRecord[] }>('/api/time-attendance/labor-groups', {}, 'Unable to load labor groups.');
  return response.data;
}

export async function createLaborGroup(payload: LaborGroupPayload) {
  const response = await apiRequest<{ success: true; data: LaborGroupRecord }>('/api/time-attendance/labor-groups', {
    method: 'POST',
    body: JSON.stringify(payload),
  }, 'Unable to create the labor group.');
  return response.data;
}

export async function updateLaborGroup(id: string, payload: Partial<LaborGroupPayload>) {
  const response = await apiRequest<{ success: true; data: LaborGroupRecord }>(`/api/time-attendance/labor-groups/${id}`, {
    method: 'PUT',
    body: JSON.stringify(payload),
  }, 'Unable to update the labor group.');
  return response.data;
}

export async function listRuleProfiles() {
  const response = await apiRequest<{ success: true; data: RuleProfileRecord[] }>('/api/time-attendance/rule-profiles', {}, 'Unable to load work rule profiles.');
  return response.data;
}

export async function createRuleProfile(payload: RuleProfilePayload) {
  const response = await apiRequest<{ success: true; data: RuleProfileRecord }>('/api/time-attendance/rule-profiles', {
    method: 'POST',
    body: JSON.stringify(payload),
  }, 'Unable to create the work rule profile.');
  return response.data;
}

export async function updateRuleProfile(id: string, payload: Partial<RuleProfilePayload>) {
  const response = await apiRequest<{ success: true; data: RuleProfileRecord }>(`/api/time-attendance/rule-profiles/${id}`, {
    method: 'PUT',
    body: JSON.stringify(payload),
  }, 'Unable to update the work rule profile.');
  return response.data;
}

export async function listShiftTemplates() {
  const response = await apiRequest<{ success: true; data: ShiftTemplateRecord[] }>('/api/time-attendance/shift-templates', {}, 'Unable to load shift templates.');
  return response.data;
}

export async function createShiftTemplate(payload: ShiftTemplatePayload) {
  const response = await apiRequest<{ success: true; data: ShiftTemplateRecord }>('/api/time-attendance/shift-templates', {
    method: 'POST',
    body: JSON.stringify(payload),
  }, 'Unable to create the shift template.');
  return response.data;
}

export async function updateShiftTemplate(id: string, payload: Partial<ShiftTemplatePayload>) {
  const response = await apiRequest<{ success: true; data: ShiftTemplateRecord }>(`/api/time-attendance/shift-templates/${id}`, {
    method: 'PUT',
    body: JSON.stringify(payload),
  }, 'Unable to update the shift template.');
  return response.data;
}
